# This is the main idea of the yaml file
steps: 
- name: 'gcr.io/cloud-builders/docker'
  id: Build 
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/ooioiooGT/api-tests:latest'
  - '.'


- name: 'gcr.io/cloud-builders/docker'
  id : push 
  args: 
  - 'push'
  - 'gcr.io/$PROJECT_ID/ooioiooGT/api-tests:latest'