apiVersion: apps/v1
kind: Deployment
metadata: 
  name: logan-clark
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: logan-clark
  template:
    metadata:
      labels:
        app: logan-clark
    spec: 
      containers:
        - name: logan-clark
          image: nginx
          ports:
          - containerPort: 80
          resources:
            limits: 
              cpu: 100m
              memory: 250M
            requests:
              cpu: 50m
              memory: 100M