apiVersion: apps/v1
kind: Deployment
metadata:
  name: todd-gunn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todd-gunn
  template:
    metadata:
      labels:
        app: todd-gunn
    spec:
      containers:
      - name: todd-gunn
        image: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 250M
          requests:
            cpu: 50m
            memory: 100M